### ISSUE TITLE
Vesync V2 is not working on either Hoobs or Homebridge.  The plugin is configured with logging turned on.

### ISSUE THREAD

**Issue by yogiberra** [mickgiles/homebridge-vesync#3]
Here is the configuration file segment
{
    "platform": "VesyncPlug",
    "name": "VesyncPlug",
    "username": "USER@gmail.com",
    "password": "PASSWORD",
    "debug": "True"
}

Here are the logs:
11/27/2020, 10:01:19 AM [VesyncPlug] DeviceDiscovery invoked
11/27/2020, 10:01:19 AM (node:29459) UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "tk"
11/27/2020, 10:01:19 AM at ClientRequest.setHeader (_http_outgoing.js:529:3)
11/27/2020, 10:01:19 AM at new ClientRequest (_http_client.js:243:14)
11/27/2020, 10:01:19 AM at Object.request (https.js:316:10)
11/27/2020, 10:01:19 AM at /home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:391:79
11/27/2020, 10:01:19 AM at new Promise (<anonymous>)
11/27/2020, 10:01:19 AM at Object.makeRequest (/home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:270:29)
11/27/2020, 10:01:19 AM at Object.doPost [as post] (/home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:163:25)
11/27/2020, 10:01:19 AM at EtekCityClient.getDevices (/home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/lib/client.js:48:28)
11/27/2020, 10:01:19 AM at /home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/index.js:65:28
11/27/2020, 10:01:19 AM (node:29459) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
11/27/2020, 10:01:40 AM [LevitonDecoraSmart] onGetPower Front Lights
11/27/2020, 10:01:40 AM [LevitonDecoraSmart] onGetPower Ilene’s Lamp

11/27/2020, 10:02:19 AM [VesyncPlug] DeviceDiscovery invoked
11/27/2020, 10:02:19 AM (node:29459) UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "tk"
11/27/2020, 10:02:19 AM at ClientRequest.setHeader (_http_outgoing.js:529:3)
11/27/2020, 10:02:19 AM at new ClientRequest (_http_client.js:243:14)
11/27/2020, 10:02:19 AM at Object.request (https.js:316:10)
11/27/2020, 10:02:19 AM at /home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:391:79
11/27/2020, 10:02:19 AM at new Promise (<anonymous>)
11/27/2020, 10:02:19 AM at Object.makeRequest (/home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:270:29)
11/27/2020, 10:02:19 AM at Object.doPost [as post] (/home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:163:25)
11/27/2020, 10:02:19 AM at EtekCityClient.getDevices (/home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/lib/client.js:48:28)
11/27/2020, 10:02:19 AM at /home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/index.js:65:28
11/27/2020, 10:02:19 AM (node:29459) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
11/27/2020, 10:03:19 AM [VesyncPlug] DeviceDiscovery invoked
11/27/2020, 10:03:19 AM (node:29459) UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "tk"
11/27/2020, 10:03:19 AM at ClientRequest.setHeader (_http_outgoing.js:529:3)
11/27/2020, 10:03:19 AM at new ClientRequest (_http_client.js:243:14)
11/27/2020, 10:03:19 AM at Object.request (https.js:316:10)
11/27/2020, 10:03:19 AM at /home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:391:79
11/27/2020, 10:03:19 AM at new Promise (<anonymous>)
11/27/2020, 10:03:19 AM at Object.makeRequest (/home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:270:29)
11/27/2020, 10:03:19 AM at Object.doPost [as post] (/home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:163:25)
11/27/2020, 10:03:19 AM at EtekCityClient.getDevices (/home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/lib/client.js:48:28)
11/27/2020, 10:03:19 AM at /home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/index.js:65:28
11/27/2020, 10:03:19 AM (node:29459) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)

**Comment by tjenvy** [comment]
Just installed, same thing UnhandledPromiseRejectionWarning

**Comment by tjenvy** [comment]
Fixed it, wrong password.  @yogiberra check your password.

**Comment by yogiberra** [comment]
Thanks for getting back to me quickly.

What do you mean “Fixed it” in your email.  Did you modify the Vesync plugin?

I checked my username and password on the iPhone app and the credentials I was using was exactly the same.  I uninstalled and reinstalled  vesync v2 on hoobs and  still get this error, see below.

How confident are you that I have a entered incorrect credentials. Could this be a firewall issue?

This is the log:

1/30/2020, 10:36:07 AM (node:15606) UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "tk"11/30/2020, 10:36:07 AM at ClientRequest.setHeader (_http_outgoing.js:529:3)11/30/2020, 10:36:08 AM at new ClientRequest (_http_client.js:243:14)11/30/2020, 10:36:08 AM at Object.request (https.js:316:10)11/30/2020, 10:36:08 AM at /home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:391:7911/30/2020, 10:36:08 AM at new Promise (<anonymous>)11/30/2020, 10:36:08 AM at Object.makeRequest (/home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:270:29)11/30/2020, 10:36:08 AM at Object.doPost [as post] (/home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:163:25)11/30/2020, 10:36:08 AM at EtekCityClient.getDevices (/home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/lib/client.js:48:28)11/30/2020, 10:36:08 AM at /home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/index.js:65:2811/30/2020, 10:36:08 AM (node:15606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

Sent from Mail for Windows 10

**Comment by tjenvy** [comment]
I run  a limited number of passwords (I know its bad). But after looking at the password for the veSync app, I entered it and restarted and everything started working.  I went back in, changed the password, got the Unhandled promise rejection errors again.

Heres the issue, that could be related to any number of function.s. My knowledge of these plugins is user +. Nothing major.  So it may not work for you but for me at least it was a simple fix.

**Comment by yogiberra** [comment]
Thank you so much for responding.  I will try a change of passwords.  I appreciate your efforts.  
Eric

**Comment by yogiberra** [comment]
I am not having any luck.  I changed my password twice and still received this error.  I wish something would work.

ClientRequest.setHeader (_http_outgoing.js:529:3)11/30/2020, 3:35:13 PM at new ClientRequest (_http_client.js:243:14)11/30/2020, 3:35:13 PM at Object.request (https.js:316:10)11/30/2020, 3:35:13 PM at /home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:391:7911/30/2020, 3:35:13 PM at new Promise (<anonymous>)11/30/2020, 3:35:13 PM at Object.makeRequest (/home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:270:29)11/30/2020, 3:35:13 PM at Object.doPost [as post] (/home/hoobs/.hoobs/node_modules/hyper-request/hrequest.js:163:25)11/30/2020, 3:35:13 PM at EtekCityClient.getDevices (/home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/lib/client.js:48:28)11/30/2020, 3:35:13 PM at /home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/index.js:65:2811/30/2020, 3:35:13 PM (node:1718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

Sent from Mail for Windows 10

**Comment by yogiberra** [comment]
I changed passwords.  No luck.  I have tried passwords with with % $ # (and other standard symbols) and alphanumerics (upper and lower case)
.  I still get the same error.  Anyone else with suggestions?  (I am running this plugin on HOOBS)

 /home/hoobs/.hoobs/node_modules/homebridge-vesync-v2/index.js:65:28
11/30/2020, 3:49:13 PM (node:1718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 48)

**Comment by mickgiles** [comment]
If you are running this on Windows they problem may have been the error fixed in issue #8 
Try the latest build and see if this is resolved for you

**Comment by mickgiles** [comment]
I have created a new project with more device coverage and will be easier to support moving forward. This project will be archived. Please see https://github.com/mickgiles/homebridge-tsvesync for the new plugin and to report any issues.
